spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://1authority-interns.1rivet.com:5004
          jwkSeturi: https://1authority-interns.1rivet.com:5004/.well-known/openid-configuration/jwks
          audiences: DeskBookApi
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DeskBookDev;encrypt=true;trustServerCertificate=true
    username: sa
    password: Admin@123
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
   port: 9443
#   ssl: 
#     enabled: true
#     key-store-type: PKCS12
#     key-store: file:C:\\deskbook-userapi\\deskbook.p12
#     key-store-password: admin
#     key-alias: dev-deskbook-userapi.1rivet.com

# Cors Configuration
web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET,PUT,
    allowed-headers: "Requestor-Type"
    exposed-headers: "X-Get-Header"

          
          
